[project]
name = "intro-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "langchain[google-gemini,google-genai]>=1.4.2",
    "langchain-classic>=1.0.8",
    "langchain-community>=0.4.2",
    "langchain-ollama>=1.1.0",
    "langchain-text-splitters>=1.1.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "uv>=0.12.18",
]
